version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    ports:
      - "27017:27017"
